name: E2E Sign and Submit

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  e2e:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        ports:
          - 5433:5432
        env:
          POSTGRES_PASSWORD: password
          POSTGRES_DB: beacon_runner
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 5s
          --health-timeout 5s
          --health-retries 20
      redis:
        image: redis:7
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping || exit 1"
          --health-interval 5s
          --health-timeout 5s
          --health-retries 20

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Build runner
        run: go build -o bin/runner ./cmd/runner

      - name: Build sigtool
        run: go build -o sigtool ./cmd/sigtool

      - name: Start runner API
        env:
          DATABASE_URL: postgres://postgres:password@localhost:5433/beacon_runner?sslmode=disable
          REDIS_URL: redis://localhost:6379
        run: |
          nohup ./bin/runner > runner.log 2>&1 &
          echo $! > runner.pid

      - name: Wait for API /health
        run: |
          for i in {1..60}; do
            if curl -fsS http://localhost:8090/health >/dev/null; then
              echo "API ready"; exit 0;
            fi
            sleep 1
          done
          echo "API did not become ready in time" >&2
          tail -n 200 runner.log || true
          exit 1

      - name: Run E2E sign→submit
        run: |
          chmod +x scripts/e2e-sign-submit.sh
          ./scripts/e2e-sign-submit.sh

      - name: Upload runner logs on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: runner-logs
          path: runner.log
