name: Portal CI/CD

on:
  push:
    branches: [ main ]
    paths:
      - 'portal/**'
      - 'docs/**'
      - 'scripts/**'
      - 'netlify.toml'
      - 'package.json'
      - 'package-lock.json'
      - '.github/workflows/portal.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'portal/**'
      - 'docs/**'
      - 'scripts/**'
      - 'netlify.toml'
      - 'package.json'
      - 'package-lock.json'
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install root deps
        run: npm ci

      - name: Install portal deps
        working-directory: portal
        run: npm ci

      - name: Lint / Validate (lightweight)
        run: |
          npm run validate:schemas
          npm run test:portal
          npm run test:build
          npm run test:api

      - name: Build site (dist/)
        env:
          DOCS_BUILD_CID: ${{ secrets.DOCS_BUILD_CID || '' }}
          VITE_IPFS_GATEWAY: ${{ secrets.VITE_IPFS_GATEWAY || 'https://ipfs.io' }}
          VITE_ENABLE_WS: ${{ secrets.VITE_ENABLE_WS || '1' }}
          VITE_API_BASE: ${{ secrets.VITE_API_BASE || 'https://projectbeacon.netlify.app' }}
          # Optionally force WS base to Railway during rollout
          VITE_WS_BASE: ${{ secrets.VITE_WS_BASE || '' }}
        run: |
          npm run build:static
          npm run build:docs
          npm run postbuild:cid
          npm run build:docs:with-cid
          # Build portal bundle and copy into dist/portal
          (cd portal && npm run build)
          mkdir -p dist/portal
          cp -R portal/dist/* dist/portal/

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: portal-dist
          path: dist

  e2e:
    # Optional: run on workflow_dispatch or enable on PRs as needed
    if: ${{ github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install deps
        run: |
          npm ci
          npx playwright install --with-deps

      - name: Build site (for e2e)
        run: npm run test:deployment

  deploy-netlify:
    needs: [ build-and-test ]
    runs-on: ubuntu-latest
    timeout-minutes: 15
    if: ${{ secrets.NETLIFY_AUTH_TOKEN && secrets.NETLIFY_SITE_ID }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: portal-dist
          path: dist

      - name: Deploy to Netlify
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        run: |
          npx netlify-cli deploy --dir=dist --site=$NETLIFY_SITE_ID --auth=$NETLIFY_AUTH_TOKEN --prod

      - name: Post-deploy smoke checks
        run: |
          set -e
          echo "Checking portal availability"
          curl -sSfL https://projectbeacon.netlify.app >/dev/null
          echo "Checking WS hint (HTTP GET) via Netlify proxy"
          curl -sSfL https://projectbeacon.netlify.app/ws | jq . || true
