name: PR Checks

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        
    - name: Install dependencies
      run: |
        npm ci
        cd portal && npm ci
        
    - name: Run portal tests
      run: cd portal && npm test -- --watchAll=false
      
    - name: Build portal
      run: cd portal && npm run build
      
    - name: Validate build output
      run: node scripts/test-build-output.js
      
    - name: Install Playwright
      run: npx playwright install --with-deps chromium
      
    - name: Run CORS integration tests
      run: npx playwright test
      
    - name: Comment PR with test results
      uses: actions/github-script@v7
      if: always()
      with:
        script: |
          const { context } = require('@actions/github');
          const jobStatus = '${{ job.status }}';
          const runUrl = `${context.payload.repository.html_url}/actions/runs/${context.runId}`;
          
          const body = jobStatus === 'success' 
            ? `✅ **All tests passed!** 
            
            - Portal unit tests: ✅
            - Build validation: ✅  
            - CORS integration tests: ✅
            
            Ready for review and merge.`
            : `❌ **Tests failed**
            
            Please check the [test results](${runUrl}) and fix any issues before merging.`;
            
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: body
          });
