global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alerts.yaml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'project-beacon-runner'
    static_configs:
      - targets: ['host.docker.internal:8090']
    metrics_path: '/api/v1/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

  - job_name: 'yagna-daemon'
    static_configs:
      - targets: ['host.docker.internal:7465']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s
