[build]
  # Conservative build approach with explicit steps
  command = "npm install --no-audit --legacy-peer-deps && cd portal && npm install --no-audit --legacy-peer-deps && cd .. && npm run build:static && npm run build:docs && npm run postbuild:cid && npm run build:docs:with-cid && npm run build:portal && npm run build:finalize"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--no-audit --fund=false --legacy-peer-deps"
  # Increase memory for Node.js builds
  NODE_OPTIONS = "--max-old-space-size=4096"
  # Default IPFS gateway for production portal links (overridable per-deploy)
  VITE_IPFS_GATEWAY = "https://ipfs.io"
  # Enable WebSocket client in portal by default
  VITE_ENABLE_WS = "1"
  # Use same-origin for API base; portal code appends /api/v1
  VITE_API_BASE = "https://projectbeacon.netlify.app"
  # Optional: direct diffs backend base (portal also uses same-origin proxy /backend-diffs)
  # VITE_DIFFS_BASE = "https://backend-diffs-production.up.railway.app"
  # If needed, set these in Netlify UI instead of hardcoding:
  # VITE_HYBRID_BASE = "https://project-beacon-production.up.railway.app"
  # VITE_WS_BASE = "wss://project-beacon-production.up.railway.app"
  # Google Maps API key for production (set in Netlify dashboard)
  # VITE_GOOGLE_MAPS_API_KEY = "REPLACE_WITH_NEW_KEY"

# Ensure clean URLs and proper SPA fallback for Docusaurus under /docs
[[redirects]]
  from = "/docs/*"
  to = "/docs/index.html"
  status = 200

[[redirects]]
  from = "/docs"
  to = "/docs/index.html"
  status = 200

# Portal assets should be served directly (not redirected)
[[redirects]]
  from = "/portal/assets/*"
  to = "/portal/assets/:splat"
  status = 200

# Portal SPA fallback (but exclude assets)
[[redirects]]
  from = "/portal/*"
  to = "/portal/index.html"
  status = 200

[[redirects]]
  from = "/portal"
  to = "/portal/index.html"
  status = 200

# Demo results static files
[[redirects]]
  from = "/demo-results/*"
  to = "/demo-results/:splat"
  status = 200

# API proxy to runner (avoids CORS)
[[redirects]]
  from = "/api/v1/*"
  to = "https://beacon-runner-change-me.fly.dev/api/v1/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/health"
  to = "https://beacon-runner-change-me.fly.dev/health"
  status = 200
  force = true

# Hybrid router proxy (avoids CORS)
[[redirects]]
  from = "/hybrid/*"
  to = "https://project-beacon-production.up.railway.app/:splat"
  status = 200
  force = true

# Diffs backend proxy (avoids CORS); portal can call /backend-diffs/*
[[redirects]]
  from = "/backend-diffs/*"
  to = "https://backend-diffs-production.up.railway.app/:splat"
  status = 200
  force = true

# WebSocket proxy to Railway hybrid router
# Use same-origin ws URL in the portal (e.g., wss://<site>/ws) and proxy here.
[[redirects]]
  from = "/ws"
  to = "https://project-beacon-production.up.railway.app/ws"
  status = 200
  force = true

[[redirects]]
  from = "/ws/*"
  to = "https://project-beacon-production.up.railway.app/ws/:splat"
  status = 200
  force = true

# Default root fallback for the one-pager (no SPA framework, just static)
# No catch-all needed at root; index.html served by default.

# Caching for built assets and security headers
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    Content-Security-Policy = "default-src 'self'; img-src 'self' data: https:; font-src 'self' https: data:; script-src 'self' 'unsafe-inline' https://maps.googleapis.com https://maps.gstatic.com; style-src 'self' 'unsafe-inline' https:; connect-src 'self' https: wss:; frame-ancestors 'self'"
