[build]
  # Robust build using unified npm script with safe installs and clear errors
  command = "bash -lc 'set -euo pipefail; echo Node $(node -v); echo NPM $(npm -v); npm ci --no-audit --fund=false || npm install --no-audit --legacy-peer-deps; if [ -f portal/package-lock.json ]; then npm ci --prefix portal --no-audit --fund=false; else npm install --prefix portal --no-audit --fund=false; fi; npm run build'"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--no-audit --fund=false --legacy-peer-deps"
  # Increase memory for Node.js builds
  NODE_OPTIONS = "--max-old-space-size=4096"
  # Default IPFS gateway for production portal links (overridable per-deploy)
  VITE_IPFS_GATEWAY = "https://ipfs.io"
  # WebSocket client disabled by default (no WS server running)
  VITE_ENABLE_WS = "0"
  # Use same-origin for API base; portal code appends /api/v1
  VITE_API_BASE = "https://projectbeacon.netlify.app"
  # Direct diffs backend base (avoid relying on proxy while we stabilize redirects)
  VITE_DIFFS_BASE = "https://backend-diffs-production.up.railway.app"
  # If needed, set these in Netlify UI instead of hardcoding:
  # VITE_HYBRID_BASE = "https://project-beacon-production.up.railway.app"
  # VITE_WS_BASE = "wss://project-beacon-production.up.railway.app"
  # Restrict Google Maps API key to only our domain (set in Google Cloud Console)
  # VITE_GOOGLE_MAPS_API_KEY = "REPLACE_WITH_NEW_KEY"

# All redirects now handled by dist/_redirects (single source of truth)
# Generated by scripts/write-redirects.js with environment parameterization

# Caching for built assets and security headers
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    Content-Security-Policy = "default-src 'self'; img-src 'self' data: https:; font-src 'self' https: data:; script-src 'self' 'unsafe-inline' https://project-beacon-production.up.railway.app https://maps.googleapis.com https://maps.gstatic.com; style-src 'self' 'unsafe-inline' https:; connect-src 'self' https:; frame-ancestors 'self'; referrer 'strict-origin-when-cross-origin'"
