name: Build and Push LLM Benchmark Containers

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - 'Website/llm-benchmark/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Build and push LLM containers
        run: |
          cd Website/llm-benchmark
          
          # Copy shared files to each container directory
          echo "Copying shared files..."
          cp benchmark.py questions.json scoring.py llama-3.2-1b/
          cp benchmark.py questions.json scoring.py qwen-2.5-1.5b/
          cp benchmark.py questions.json scoring.py mistral-7b/
          
          # Build and push Llama 3.2-1B container
          echo "Building and pushing Llama 3.2-1B container..."
          cd llama-3.2-1b
          docker build -t ghcr.io/${{ github.repository_owner }}/project-beacon-llama-3.2-1b:latest .
          docker build -t ghcr.io/${{ github.repository_owner }}/project-beacon-llama-3.2-1b:v1.0.0 .
          docker push ghcr.io/${{ github.repository_owner }}/project-beacon-llama-3.2-1b:latest
          docker push ghcr.io/${{ github.repository_owner }}/project-beacon-llama-3.2-1b:v1.0.0
          cd ..
          
          # Build and push Qwen 2.5-1.5B container
          echo "Building and pushing Qwen 2.5-1.5B container..."
          cd qwen-2.5-1.5b
          docker build -t ghcr.io/${{ github.repository_owner }}/project-beacon-qwen-2.5-1.5b:latest .
          docker build -t ghcr.io/${{ github.repository_owner }}/project-beacon-qwen-2.5-1.5b:v1.0.0 .
          docker push ghcr.io/${{ github.repository_owner }}/project-beacon-qwen-2.5-1.5b:latest
          docker push ghcr.io/${{ github.repository_owner }}/project-beacon-qwen-2.5-1.5b:v1.0.0
          cd ..
          
          # Build and push Mistral 7B container
          echo "Building and pushing Mistral 7B container..."
          cd mistral-7b
          docker build -t ghcr.io/${{ github.repository_owner }}/project-beacon-mistral-7b:latest .
          docker build -t ghcr.io/${{ github.repository_owner }}/project-beacon-mistral-7b:v1.0.0 .
          docker push ghcr.io/${{ github.repository_owner }}/project-beacon-mistral-7b:latest
          docker push ghcr.io/${{ github.repository_owner }}/project-beacon-mistral-7b:v1.0.0
          cd ..
          
          # Clean up copied files
          echo "Cleaning up..."
          rm llama-3.2-1b/benchmark.py llama-3.2-1b/questions.json llama-3.2-1b/scoring.py
          rm qwen-2.5-1.5b/benchmark.py qwen-2.5-1.5b/questions.json qwen-2.5-1.5b/scoring.py
          rm mistral-7b/benchmark.py mistral-7b/questions.json mistral-7b/scoring.py
          
          echo "All containers built and pushed successfully!"
